version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    volumes:
      - ${PWD}/db:${PWD}/db
      - ${PWD}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
