export default {
  id: '20687432',
  displayName: 'Jeason',
  username: 'rhy0u',
  profileUrl: 'https://github.com/rhy0u',
  emails: [{ value: 'jsn.centaure@gmail.com' }],
  photos: [{ value: 'https://avatars0.githubusercontent.com/u/20687432?v=4' }],
  provider: 'github',
  _raw:
    '{"login":"rhy0u","id":20687432,"avatar_url":"https://avatars0.githubusercontent.com/u/20687432?v=4","gravatar_id":"","url":"https://api.github.com/users/rhy0u","html_url":"https://github.com/rhy0u","followers_url":"https://api.github.com/users/rhy0u/followers","following_url":"https://api.github.com/users/rhy0u/following{/other_user}","gists_url":"https://api.github.com/users/rhy0u/gists{/gist_id}","starred_url":"https://api.github.com/users/rhy0u/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rhy0u/subscriptions","organizations_url":"https://api.github.com/users/rhy0u/orgs","repos_url":"https://api.github.com/users/rhy0u/repos","events_url":"https://api.github.com/users/rhy0u/events{/privacy}","received_events_url":"https://api.github.com/users/rhy0u/received_events","type":"User","site_admin":false,"name":"Jeason","company":null,"blog":"","location":"Paris","email":"jsn.centaure@gmail.com","hireable":null,"bio":null,"public_repos":10,"public_gists":1,"followers":1,"following":0,"created_at":"2016-07-27T17:13:49Z","updated_at":"2018-01-21T14:10:55Z"}',
  _json: {
    login: 'rhy0u',
    id: 20687432,
    avatar_url: 'https://avatars0.githubusercontent.com/u/20687432?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/rhy0u',
    html_url: 'https://github.com/rhy0u',
    followers_url: 'https://api.github.com/users/rhy0u/followers',
    following_url: 'https://api.github.com/users/rhy0u/following{/other_user}',
    gists_url: 'https://api.github.com/users/rhy0u/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/rhy0u/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/rhy0u/subscriptions',
    organizations_url: 'https://api.github.com/users/rhy0u/orgs',
    repos_url: 'https://api.github.com/users/rhy0u/repos',
    events_url: 'https://api.github.com/users/rhy0u/events{/privacy}',
    received_events_url: 'https://api.github.com/users/rhy0u/received_events',
    type: 'User',
    site_admin: false,
    name: 'Jeason',
    company: null,
    blog: '',
    location: 'Paris',
    email: 'jsn.centaure@gmail.com',
    hireable: null,
    bio: null,
    public_repos: 10,
    public_gists: 1,
    followers: 1,
    following: 0,
    created_at: '2016-07-27T17:13:49Z',
    updated_at: '2018-01-21T14:10:55Z',
  },
}
